spring:
  application:
    name: ActivateService
server:
  port: 9002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}

pivotal:
  persistenceservice:
    name: PERSISTENCESERVICE